title: norns study group
description: an open community of norns users
baseurl: /
url: https://study.norns.online
permalink: pretty
sort_by: year, month
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-feed
include: ['_pages']
collections_dir: collections
